"use client";
import { Alert, Button, Paper, Stack, Typography, Box } from "@mui/material";import { useEffect,useState } from "react";import {useParams} from "next/navigation";import AuthGuard from "@/components/AuthGuard";import DashboardShell from "@/components/dashboard/DashboardShell";import type {Ride} from "@/types/ride";import LiveMap from "@/components/maps/LiveMap";
export default function DriverRideDetails(){const {id}=useParams<{id:string}>();const [ride,setRide]=useState<Ride|null>(null);const [msg,setMsg]=useState("");const [sharing,setSharing]=useState(false);const [shareUrl,setShareUrl]=useState("");
useEffect(()=>{fetch(`/api/rides/${id}`).then(r=>r.json()).then(d=>setRide(d.ride||null));},[id]);
useEffect(()=>{if(!ride||ride.status!=="IN_PROGRESS")return;const watch=navigator.geolocation?.watchPosition(async p=>{await fetch(`/api/tracking/${id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,heading:p.coords.heading,speed:p.coords.speed})});},()=>{});return()=>{if(watch!==undefined)navigator.geolocation.clearWatch(watch)};},[ride?.status,id]);
const start=async()=>{const r=await fetch(`/api/rides/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:"IN_PROGRESS"})});const d=await r.json();if(!r.ok){setMsg(d.error);return}setRide(d.ride)};const complete=async()=>{const r=await fetch(`/api/rides/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:"COMPLETED"})});const d=await r.json();if(!r.ok){setMsg(d.error);return}setRide(d.ride)};
const cancel=async()=>{const r=await fetch(`/api/rides/${id}`,{method:"DELETE"});const d=await r.json();if(!r.ok){setMsg(d.error);return}setRide(d.ride)};
const share=async()=>{setSharing(true);const r=await fetch(`/api/tracking/share/${id}`,{method:"POST"});const d=await r.json();setSharing(false);if(!r.ok){setMsg(d.error||"Could not create tracking link");return}setShareUrl(d.url);await navigator.clipboard?.writeText(d.url);setMsg("Private tracking link copied. Send it to your trusted contacts.")};
return <AuthGuard role="DRIVER"><DashboardShell role="DRIVER">{ride?<><Typography variant="h3">{ride.pickup.name} → {ride.destination.name}</Typography><Typography sx={{mt:1,color:"text.secondary"}}>{ride.departureDate} at {ride.departureTime}</Typography><Paper elevation={0} sx={{mt:3,p:3,border:"1px solid #E5EAF2"}}><Stack gap={1}><Typography>Distance: {ride.distanceKm} km</Typography><Typography>Passenger price: R{ride.pricePerSeat}</Typography><Typography>Seats: {ride.availableSeats} / {ride.totalSeats}</Typography><Typography>Status: {ride.status?.replaceAll("_"," ").replace(/\b\w/g,(x:string)=>x.toUpperCase())}</Typography></Stack><Box sx={{mt:3}}><LiveMap pickup={ride.pickup} destination={ride.destination}/></Box><Stack direction={{xs:"column",sm:"row"}} gap={1.5} sx={{mt:3}}><Button variant="contained" onClick={start} disabled={ride.status!=="PUBLISHED"&&ride.status!=="FULL"}>Start ride</Button><Button variant="outlined" onClick={complete} disabled={ride.status!=="IN_PROGRESS"}>Complete ride</Button><Button variant="contained" onClick={share} disabled={sharing}>Share live safety link</Button><Button color="error" variant="outlined" onClick={cancel} disabled={ride.status==="CANCELLED"}>Cancel ride</Button></Stack>{shareUrl&&<Alert severity="success" sx={{mt:2}}>{shareUrl}</Alert>}{msg&&<Alert sx={{mt:2}}>{msg}</Alert>}</Paper></>:<Typography>Ride not found.</Typography>}</DashboardShell></AuthGuard>}
