import {NextResponse} from "next/server";import {db} from "@/lib/db";import {getCurrentUser} from "@/lib/auth";import {paystackRequest,kobo} from "@/lib/payments";import crypto from "node:crypto";import {calculateFees} from "@/lib/pricing";
export async function POST(req:Request){const user=await getCurrentUser();if(!user||user.role!=="RIDER")return NextResponse.json({error:"Only riders can make payments."},{status:403});const b=await req.json();const action=b.action||"BOOKING";try{
 if(action==="ADD_CARD"){const ref=`RG-CARD-${crypto.randomUUID()}`;const data=await paystackRequest("transaction/initialize",{email:user.email,amount:kobo(10),reference:ref,callback_url:process.env.PAYSTACK_CALLBACK_URL||`${new URL(req.url).origin}/rider/payments/callback`,metadata:{purpose:"ADD_CARD",userId:user.id}});await db.payment.create({data:{payerId:user.id,reference:ref,amount:.1,driverFee:0,customerFee:0,status:"PENDING",metadata:JSON.stringify({purpose:"ADD_CARD",userId:user.id})}});return NextResponse.json({authorization_url:data.authorization_url,reference:ref});}
 const riderProfile=await db.riderProfile.findUnique({where:{userId:user.id}}); if(!riderProfile || riderProfile.verificationStatus!=="VERIFIED") return NextResponse.json({error:"Please complete rider identity verification before booking a ride."},{status:403,code:"RIDER_VERIFICATION_REQUIRED"});
 const requestedRideId=String(b.rideId||"");
 const rideVerification=await db.riderRideVerification.findFirst({where:{riderId:user.id,rideId:requestedRideId,status:"VERIFIED"},orderBy:{createdAt:"desc"}});
 if(!rideVerification) return NextResponse.json({error:"Complete the live face check for this ride before payment."},{status:403,code:"RIDE_FACE_VERIFICATION_REQUIRED"});
 const ride=await db.ride.findUnique({where:{id:String(b.rideId)}});if(!ride||ride.status==="CANCELLED"||ride.availableSeats<Number(b.seatsRequested))return NextResponse.json({error:"Ride is unavailable."},{status:409});const fare=Number(ride.pricePerSeat)*Number(b.seatsRequested);const fees=calculateFees(fare);const ref=`RG-RIDE-${crypto.randomUUID()}`;const data=await paystackRequest("transaction/initialize",{email:user.email,amount:kobo(fees.totalCharge),reference:ref,callback_url:process.env.PAYSTACK_CALLBACK_URL||`${new URL(req.url).origin}/rider/payments/callback`,metadata:{purpose:"BOOKING",userId:user.id,rideId:ride.id,seatsRequested:Number(b.seatsRequested),bags:Number(b.bags||0),collectionSpot:b.collectionSpot}});await db.payment.create({data:{payerId:user.id,reference:ref,amount:fees.totalCharge,driverFee:fees.driverFee,customerFee:fees.customerFee,status:"PENDING",metadata:JSON.stringify({purpose:"BOOKING",userId:user.id,rideId:ride.id,seatsRequested:Number(b.seatsRequested),bags:Number(b.bags||0),collectionSpot:b.collectionSpot})}});return NextResponse.json({authorization_url:data.authorization_url,reference:ref,breakdown:{fare,customerFee:fees.customerFee,total:fees.totalCharge}});
}catch(e){console.error(e);return NextResponse.json({error:e instanceof Error?e.message:"Unable to initialise payment."},{status:500})}}
