"use client";
import { AppBar, Box, Button, Divider, Drawer, IconButton, List, ListItemButton, ListItemIcon, ListItemText, Toolbar, Typography } from "@mui/material";
import MenuIcon from "@mui/icons-material/Menu"; import LogoutIcon from "@mui/icons-material/Logout"; import DashboardRoundedIcon from "@mui/icons-material/DashboardRounded"; import DirectionsCarRoundedIcon from "@mui/icons-material/DirectionsCarRounded"; import EventSeatRoundedIcon from "@mui/icons-material/EventSeatRounded"; import VerifiedRoundedIcon from "@mui/icons-material/VerifiedRounded"; import PersonRoundedIcon from "@mui/icons-material/PersonRounded"; import ShieldRoundedIcon from "@mui/icons-material/ShieldRounded"; import CreditCardRoundedIcon from "@mui/icons-material/CreditCardRounded"; import AddRoundedIcon from "@mui/icons-material/AddRounded"; import SearchRoundedIcon from "@mui/icons-material/SearchRounded";
import Link from "next/link"; import { usePathname,useRouter } from "next/navigation"; import { useState } from "react"; import NotificationBell from "@/components/common/NotificationBell"; import VerificationGate from "@/components/verification/VerificationGate";

export default function DashboardShell({role,children}:{role:"RIDER"|"DRIVER"|"AGENT"|"ADMIN";children:React.ReactNode}){
 const [open,setOpen]=useState(false); const router=useRouter(); const pathname=usePathname(); const prefix=role==="DRIVER"?"/driver":role==="RIDER"?"/rider":role==="AGENT"?"/agent":"/backoffice";
 const links=role==="DRIVER"?[["Overview","/driver/dashboard",DashboardRoundedIcon],["My rides","/driver/rides",DirectionsCarRoundedIcon],["Bookings","/driver/bookings",EventSeatRoundedIcon],["Profile","/driver/profile",PersonRoundedIcon]]:role==="RIDER"?[["Overview","/rider/dashboard",DashboardRoundedIcon],["Find a ride","/rider/rides",DirectionsCarRoundedIcon],["Bookings","/rider/bookings",EventSeatRoundedIcon],["Trips","/rider/trips",DirectionsCarRoundedIcon],["Payments","/rider/payments",CreditCardRoundedIcon],["Profile","/rider/profile",PersonRoundedIcon]]:role==="AGENT"?[["Operations","/agent/dashboard",DashboardRoundedIcon],["Driver verification","/agent/drivers",VerifiedRoundedIcon],["Rider verification","/agent/riders",VerifiedRoundedIcon],["Safety reports","/agent/reports",ShieldRoundedIcon],["Support","/agent/support",EventSeatRoundedIcon]]:[["Command center","/backoffice",DashboardRoundedIcon],["Drivers","/agent/drivers",DirectionsCarRoundedIcon],["Agents","/backoffice/agents",PersonRoundedIcon],["Safety","/agent/reports",ShieldRoundedIcon],["Payments","/backoffice/payments",CreditCardRoundedIcon],["Experience","/backoffice/experience",DashboardRoundedIcon]];
 const logout=async()=>{await fetch('/api/auth/logout',{method:'POST'});router.replace('/login')};
 const nav=<List sx={{px:1.25}}>{links.map(([label,href,Icon]:any)=>{const active=pathname===href||pathname.startsWith(href+'/');return <ListItemButton component={Link} href={href} key={href} onClick={()=>setOpen(false)} sx={{minHeight:46,borderRadius:1.5,mb:.4,py:.7,color:active?'#111318':'#626B78',bgcolor:active?'#EEF2FF':'transparent','&:hover':{bgcolor:'#F3F5F8',color:'#111318'}}}><ListItemIcon sx={{minWidth:38,color:'inherit'}}><Icon fontSize="small"/></ListItemIcon><ListItemText primary={label} primaryTypographyProps={{fontWeight:active?800:650,fontSize:'.9rem'}}/></ListItemButton>})}</List>;
 return <Box sx={{minHeight:'100vh',background:'#F5F6F8',color:'#111318'}}>
 <AppBar position="fixed" elevation={0} sx={{background:'rgba(255,255,255,.94)',backdropFilter:'blur(18px)',color:'#111318',borderBottom:'1px solid #E3E6EB',zIndex:1200}}><Toolbar sx={{gap:1.5,minHeight:{xs:64,md:70},px:{xs:1.5,md:2.5}}}><IconButton sx={{display:{md:'none'}}} onClick={()=>setOpen(true)} aria-label="Open navigation"><MenuIcon/></IconButton><Typography component={Link} href={`${prefix}/dashboard`} sx={{textDecoration:'none',color:'inherit',fontWeight:950,fontSize:'1.35rem',letterSpacing:'-.045em'}}>Rea<span style={{color:'#315CD6'}}>Gae</span></Typography><Box sx={{display:{xs:'none',md:'flex'},alignItems:'center',ml:4,px:1.5,py:.7,bgcolor:'#F5F6F8',color:'#7A8390',gap:1,minWidth:230}}><SearchRoundedIcon fontSize="small"/><Typography variant="body2">Search</Typography></Box><Box sx={{flex:1}}/><Typography variant="body2" sx={{display:{xs:'none',sm:'block'},fontWeight:700,color:'#626B78'}}>{role==='DRIVER'?'Driver workspace':role==='RIDER'?'Rider workspace':role==='AGENT'?'Operations':'Admin console'}</Typography><NotificationBell/><IconButton onClick={logout} aria-label="Log out"><LogoutIcon fontSize="small"/></IconButton></Toolbar></AppBar>
 <Drawer open={open} onClose={()=>setOpen(false)} ModalProps={{keepMounted:true}}><Box sx={{width:270,p:2}}><Typography sx={{fontWeight:950,fontSize:'1.35rem',p:1.5}}>Rea<span style={{color:'#315CD6'}}>Gae</span></Typography><Divider sx={{mb:1}}/>{nav}</Box></Drawer>
 <Box sx={{display:'flex',pt:{xs:8,md:8.75}}}><Box component="aside" sx={{display:{xs:'none',md:'block'},width:244,position:'fixed',top:70,bottom:0,borderRight:'1px solid #E3E6EB',background:'#fff',py:2,overflowY:'auto'}}><Box sx={{px:2.2,pb:1.5}}><Typography variant="caption" sx={{fontWeight:850,color:'#8A929D',textTransform:'uppercase',letterSpacing:'.09em'}}>Workspace</Typography></Box>{nav}<Divider sx={{mx:2,my:1.5}}/><Box sx={{px:2}}><Button component={Link} href={role==='DRIVER'?'/driver/rides/create':role==='RIDER'?'/rider/rides':role==='AGENT'?'/agent/drivers':'/backoffice/agents'} fullWidth variant="contained" startIcon={role==='DRIVER'?<AddRoundedIcon/>:role==='RIDER'?<DirectionsCarRoundedIcon/>:<DashboardRoundedIcon/>}>{role==='DRIVER'?'Post a ride':role==='RIDER'?'Find a ride':role==='AGENT'?'Review cases':'Manage agents'}</Button></Box></Box><Box component="main" sx={{flex:1,minWidth:0,width:{xs:'100%',md:'calc(100% - 244px)'},ml:{md:'244px'},px:{xs:1.5,sm:2.5,lg:4},pb:7,overflowX:'hidden'}}>{children}</Box></Box>
 {role==='RIDER' && <VerificationGate/>}
 </Box>
}
