"use client";
import { AppBar, Avatar, Box, Button, Chip, Divider, Drawer, IconButton, List, ListItemButton, ListItemIcon, ListItemText, Toolbar, Typography } from "@mui/material";
import MenuIcon from "@mui/icons-material/Menu"; import LogoutIcon from "@mui/icons-material/Logout"; import DashboardRoundedIcon from "@mui/icons-material/DashboardRounded"; import DirectionsCarRoundedIcon from "@mui/icons-material/DirectionsCarRounded"; import EventSeatRoundedIcon from "@mui/icons-material/EventSeatRounded"; import VerifiedRoundedIcon from "@mui/icons-material/VerifiedRounded"; import PersonRoundedIcon from "@mui/icons-material/PersonRounded"; import StarRoundedIcon from "@mui/icons-material/StarRounded"; import LuggageRoundedIcon from "@mui/icons-material/LuggageRounded"; import AddCircleRoundedIcon from "@mui/icons-material/AddCircleRounded";
import Link from "next/link"; import { usePathname,useRouter } from "next/navigation"; import { useState } from "react"; import NotificationBell from "@/components/common/NotificationBell"; import Mascot from "@/components/common/Mascot";
export default function DashboardShell({role,children}:{role:"RIDER"|"DRIVER"|"AGENT"|"ADMIN";children:React.ReactNode}){
 const [open,setOpen]=useState(false); const router=useRouter(); const pathname=usePathname(); const prefix=role==="DRIVER"?"/driver":role==="RIDER"?"/rider":role==="AGENT"?"/agent":"/backoffice";
 const links=role==="DRIVER"?[["Dashboard","/driver/dashboard",DashboardRoundedIcon],["My Rides","/driver/rides",DirectionsCarRoundedIcon],["Bookings","/driver/bookings",EventSeatRoundedIcon],["Profile","/driver/profile",PersonRoundedIcon]]:role==="RIDER"?[["Dashboard","/rider/dashboard",DashboardRoundedIcon],["Find a Ride","/rider/rides",DirectionsCarRoundedIcon],["Bookings","/rider/bookings",EventSeatRoundedIcon],["Trips","/rider/trips",LuggageRoundedIcon],["Payments","/rider/payments",EventSeatRoundedIcon],["Profile","/rider/profile",PersonRoundedIcon]]:role==="AGENT"?[["Operations","/agent/dashboard",DashboardRoundedIcon],["Driver Verification","/agent/drivers",VerifiedRoundedIcon],["Rider Verification","/agent/riders",VerifiedRoundedIcon],["Safety Reports","/agent/reports",StarRoundedIcon],["Support","/agent/support",EventSeatRoundedIcon]]:[["Command Center","/backoffice",DashboardRoundedIcon],["Drivers","/agent/drivers",DirectionsCarRoundedIcon],["Agents","/backoffice/agents",PersonRoundedIcon],["Safety","/agent/reports",StarRoundedIcon],["Payments","/backoffice/payments",EventSeatRoundedIcon],["Experience","/backoffice/experience",StarRoundedIcon]];
 const logout=async()=>{await fetch('/api/auth/logout',{method:'POST'});router.replace('/login')};
 const nav=<List sx={{px:1.5}}>{links.map(([label,href,Icon]:any)=>{const active=pathname===href||pathname.startsWith(href+'/');return <ListItemButton component={Link} href={href} key={href} onClick={()=>setOpen(false)} sx={{borderRadius:3,mb:.6,py:1.15,color:active?'primary.main':'text.secondary',bgcolor:active?'rgba(91,108,255,.10)':'transparent','&:hover':{bgcolor:'rgba(91,108,255,.08)'}}}><ListItemIcon sx={{minWidth:38,color:'inherit'}}><Icon/></ListItemIcon><ListItemText primary={label} primaryTypographyProps={{fontWeight:active?850:650}}/></ListItemButton>})}</List>;
 return <Box sx={{minHeight:'100vh',background:'radial-gradient(circle at 85% 10%,rgba(139,92,246,.10),transparent 28%),#F4F6FF'}}>
 <AppBar position="fixed" elevation={0} sx={{background:'rgba(255,255,255,.88)',backdropFilter:'blur(18px)',color:'text.primary',borderBottom:'1px solid',borderColor:'divider'}}><Toolbar sx={{gap:1.5,minHeight:{xs:64,md:72}}}><IconButton sx={{display:{md:'none'}}} onClick={()=>setOpen(true)}><MenuIcon/></IconButton><Typography component={Link} href={`${prefix}/dashboard`} sx={{textDecoration:'none',color:'inherit',fontWeight:950,fontSize:'1.35rem',letterSpacing:'-.04em'}}>Rea<span style={{color:'#5B6CFF'}}>Gae</span></Typography><Chip size="small" label={role==='DRIVER'?'Driver mode':role==='RIDER'?'Rider mode':role==='AGENT'?'Agent mode':'Back office'} sx={{display:{xs:'none',sm:'inline-flex'},ml:1,bgcolor:'rgba(91,108,255,.1)',color:'primary.main'}}/><Box sx={{flex:1}}/><NotificationBell/><Button sx={{display:{xs:'none',sm:'inline-flex'}}} startIcon={<LogoutIcon/>} onClick={logout}>Log out</Button><IconButton sx={{display:{xs:'inline-flex',sm:'none'}}} onClick={logout}><LogoutIcon/></IconButton></Toolbar></AppBar>
 <Drawer open={open} onClose={()=>setOpen(false)}><Box sx={{width:280,p:2}}><Typography sx={{fontWeight:950,fontSize:'1.35rem',p:2}}>Rea<span style={{color:'#5B6CFF'}}>Gae</span></Typography><Divider sx={{mb:1}}/>{nav}</Box></Drawer>
 <Box sx={{display:'flex',pt:{xs:8,md:9}}}><Box component="aside" sx={{display:{xs:'none',md:'block'},width:250,position:'fixed',top:72,bottom:0,borderRight:'1px solid',borderColor:'divider',background:'rgba(255,255,255,.72)',backdropFilter:'blur(16px)',py:2}}><Box sx={{px:2.5,pb:2}}><Mascot compact/><Typography variant="caption" color="text.secondary" sx={{display:'block',mt:1}}>Travel smarter. Travel together.</Typography></Box>{nav}<Divider sx={{mx:2,my:1}}/><Box sx={{px:2}}><Button component={Link} href={role==='DRIVER'?'/driver/rides/create':role==='RIDER'?'/rider/rides':role==='AGENT'?'/agent/drivers':'/backoffice/agents'} fullWidth variant="contained" startIcon={role==='DRIVER'?<AddCircleRoundedIcon/>:role==='RIDER'?<DirectionsCarRoundedIcon/>:<DashboardRoundedIcon/>}>{role==='DRIVER'?'Post a ride':role==='RIDER'?'Find a ride':role==='AGENT'?'Review drivers':'Manage agents'}</Button></Box></Box><Box component="main" sx={{width:'100%',ml:{md:'250px'},px:{xs:2,sm:3,lg:5},pb:6}}>{children}</Box></Box></Box>
}
