"use client";
import { Alert, Box, Button, Chip, Paper, Stack, Typography } from "@mui/material";
import { useEffect, useState } from "react";
import AuthGuard from "@/components/AuthGuard"; import DashboardShell from "@/components/dashboard/DashboardShell";
import CheckCircleRoundedIcon from "@mui/icons-material/CheckCircleRounded"; import Face6RoundedIcon from "@mui/icons-material/Face6Rounded"; import BadgeRoundedIcon from "@mui/icons-material/BadgeRounded";
export default function RiderVerification(){const [p,setP]=useState<any>();const [doc,setDoc]=useState<any>();const [faceUrl,setFaceUrl]=useState("");const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);
 const load=()=>fetch('/api/verification/rider').then(r=>r.json()).then(d=>{setP(d.profile);setDoc(d.document)}); useEffect(()=>{load()},[]);
 const upload=async(file:File)=>{setBusy(true);const reader=new FileReader();reader.onload=async()=>{const r=await fetch('/api/verification/rider',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fileName:file.name,mimeType:file.type,data:reader.result})});const d=await r.json();setBusy(false);setMsg(d.error||d.message);if(r.ok)load()};reader.readAsDataURL(file)};
 const startFace=async()=>{setBusy(true);const r=await fetch('/api/verification/face',{method:'POST'});const d=await r.json();setBusy(false);if(!r.ok){setMsg(d.error);return}setFaceUrl(d.url);setMsg('Live face check started. Open the secure link on your phone.')};
 const status=p?.verificationStatus; return <AuthGuard role="RIDER"><DashboardShell role="RIDER"><Typography variant="h3">A safer ReaGae starts with you</Typography><Typography color="text.secondary" sx={{mt:1,maxWidth:760}}>Before you book a ride, we verify your identity with your ID and a live face check. It protects you, your driver and the people who rely on us to know who was on a journey.</Typography>{msg&&<Alert sx={{mt:2}} severity="info">{msg}</Alert>}<Paper elevation={0} sx={{mt:3,p:{xs:2,md:4},borderRadius:5,border:'1px solid',borderColor:'divider'}}><Stack gap={2.5}><Stack direction="row" justifyContent="space-between" alignItems="center"><Box><Typography variant="h5">Identity check</Typography><Typography color="text.secondary">Two steps. One verified rider profile.</Typography></Box><Chip label={status?.replaceAll('_',' ')||'Not started'} color={status==='VERIFIED'?'success':'default'}/></Stack><Paper elevation={0} sx={{p:2.5,bgcolor:'rgba(91,108,255,.07)',borderRadius:4}}><Stack direction="row" gap={2} alignItems="center"><BadgeRoundedIcon color="primary"/><Box sx={{flex:1}}><Typography fontWeight={850}>1 · Government ID</Typography><Typography variant="body2" color="text.secondary">Upload one clear identity document. Existing approved IDs are recognised.</Typography></Box>{doc?.status==='APPROVED'?<CheckCircleRoundedIcon color="success"/>:<Button component="label" variant="outlined" disabled={busy}>{doc?'Replace ID':'Upload ID'}<input hidden type="file" accept="image/*,.pdf" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></Button>}</Stack></Paper><Paper elevation={0} sx={{p:2.5,bgcolor:'rgba(91,108,255,.07)',borderRadius:4}}><Stack direction="row" gap={2} alignItems="center"><Face6RoundedIcon color="primary"/><Box sx={{flex:1}}><Typography fontWeight={850}>2 · Live face check</Typography><Typography variant="body2" color="text.secondary">Use a phone camera for a live capture. Your face is checked against the submitted ID by the verification workflow.</Typography></Box>{p?.faceVerificationStatus==='PENDING_REVIEW'?<Chip label="Awaiting review"/>:<Button variant="contained" disabled={!doc||busy} onClick={startFace}>{busy?'Starting…':'Start live check'}</Button>}</Stack>{faceUrl&&<Box sx={{mt:2}}><Typography variant="body2" fontWeight={800}>Secure phone link</Typography><Typography variant="body2" sx={{wordBreak:'break-all'}} color="text.secondary">{faceUrl}</Typography><Button sx={{mt:1}} component="a" href={faceUrl} target="_blank" variant="outlined">Open live camera</Button></Box>}</Paper><Alert severity="success">Your ID and face result are sent to the verification team. Booking is enabled once the rider verification is approved.</Alert></Stack></Paper></DashboardShell></AuthGuard>}
