"use client";
import { Alert, Box, Button, Dialog, DialogContent, DialogTitle, IconButton, LinearProgress, Stack, Typography } from "@mui/material";
import CloseRoundedIcon from "@mui/icons-material/CloseRounded"; import CameraAltRoundedIcon from "@mui/icons-material/CameraAltRounded"; import VerifiedUserRoundedIcon from "@mui/icons-material/VerifiedUserRounded";
import { useEffect,useRef,useState } from "react"; import LoadingButton from "@/components/loading/LoadingButton";
export default function FaceCaptureDialog({open,mode,onClose,onComplete,rideId}:{open:boolean;mode:'INITIAL'|'RIDE';rideId?:string;onClose?:()=>void;onComplete:(result:any)=>void}){
 const videoRef=useRef<HTMLVideoElement>(null);const streamRef=useRef<MediaStream|null>(null);const [token,setToken]=useState('');const [started,setStarted]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [stage,setStage]=useState<'preparing'|'camera'>('preparing');
 useEffect(()=>{if(!open){streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;setToken('');setStarted(false);setStage('preparing');setError('');return;}let cancelled=false;setStage('preparing');setError('');fetch('/api/verification/face',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,rideId})}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not prepare verification.');const u=new URL(d.url);const parts=u.pathname.split('/');const t=decodeURIComponent(parts[parts.length-1]);if(!cancelled)setToken(t);}).catch(e=>!cancelled&&setError(e instanceof Error?e.message:'Could not prepare verification.'));return()=>{cancelled=true;streamRef.current?.getTracks().forEach(t=>t.stop())}},[open,mode,rideId]);
 const startCamera=async()=>{try{setError('');if(!token)throw new Error('Secure verification session is still preparing.');if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera access is not supported by this browser.');const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:720},height:{ideal:720}},audio:false});streamRef.current=s;setStarted(true);setStage('camera');requestAnimationFrame(async()=>{if(videoRef.current){videoRef.current.srcObject=s;await videoRef.current.play();}})}catch(e){setError(e instanceof Error?e.message:'Camera access is required.')}};
 const capture=async()=>{if(!videoRef.current||!token)return;setBusy(true);setError('');const canvas=document.createElement('canvas');canvas.width=videoRef.current.videoWidth||720;canvas.height=videoRef.current.videoHeight||720;canvas.getContext('2d')?.drawImage(videoRef.current,0,0,canvas.width,canvas.height);try{const r=await fetch('/api/verification/face/complete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,selfie:canvas.toDataURL('image/jpeg',.84)})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Face verification failed.');streamRef.current?.getTracks().forEach(t=>t.stop());onComplete(d)}catch(e){setError(e instanceof Error?e.message:'We could not submit the capture.')}finally{setBusy(false)}};
 return <Dialog open={open} fullWidth maxWidth="sm" onClose={()=>{if(!busy)onClose?.()}} disableEscapeKeyDown={busy} aria-labelledby="face-dialog-title"><DialogTitle sx={{pr:6}}><Stack direction="row" alignItems="center" gap={1.3}><Box sx={{width:42,height:42,display:'grid',placeItems:'center',bgcolor:'#EEF2FF',color:'primary.main'}}><VerifiedUserRoundedIcon/></Box><Box><Typography variant="overline" color="primary" fontWeight={900}>{mode==='RIDE'?'RIDE REQUEST':'FIRST-TIME VERIFICATION'}</Typography><Typography id="face-dialog-title" variant="h5">Confirm it’s you</Typography></Box></Stack><IconButton onClick={()=>!busy&&onClose?.()} disabled={busy} sx={{position:'absolute',right:14,top:14}} aria-label="Close"><CloseRoundedIcon/></IconButton></DialogTitle><DialogContent sx={{pb:4}}><LinearProgress variant="determinate" value={stage==='camera'?82:42} sx={{mb:2,height:4}}/><Typography variant="body2" color="text.secondary">{mode==='RIDE'?'This face check is recorded against this specific ride request and does not need agent approval.':'Your face capture is added to your first-time identity verification case for review.'}</Typography><Box sx={{mt:2,aspectRatio:'4/3',background:'#0B111A',display:'grid',placeItems:'center',position:'relative',overflow:'hidden'}}>{started?<video ref={videoRef} muted playsInline style={{width:'100%',height:'100%',objectFit:'cover',transform:'scaleX(-1)'}}/>:<Stack alignItems="center" gap={1.2} sx={{color:'rgba(255,255,255,.72)'}}><CameraAltRoundedIcon sx={{fontSize:54}}/><Typography>Camera preview</Typography></Stack>}{started&&<Box sx={{position:'absolute',inset:'11% 25%',border:'2px solid rgba(255,255,255,.85)',borderRadius:'48%',boxShadow:'0 0 0 999px rgba(0,0,0,.15)',pointerEvents:'none'}}/>}</Box>{error&&<Alert severity="error" sx={{mt:2}}>{error}</Alert>}<Stack gap={1.2} sx={{mt:2}}>{!started?<LoadingButton fullWidth variant="contained" size="large" loading={!token} onClick={startCamera} startIcon={<CameraAltRoundedIcon/>}>{token?'Enable camera':'Preparing secure check…'}</LoadingButton>:<LoadingButton fullWidth variant="contained" size="large" loading={busy} onClick={capture}>Capture and verify</LoadingButton>}<Typography variant="caption" color="text.secondary" textAlign="center">Only use your own face. The result is recorded for the safety and verification purpose described in the Privacy Policy.</Typography></Stack></DialogContent></Dialog>;
}
