"use client";
import { Alert, Box, Button, Grid, MenuItem, Paper, Stack, TextField, Typography } from "@mui/material";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import AuthGuard from "@/components/AuthGuard";
import DashboardShell from "@/components/dashboard/DashboardShell";
import type { Ride } from "@/types/ride";
import RideCard from "@/components/rides/RideCard";
import Mascot from "@/components/common/Mascot";
import Reveal from "@/components/common/Reveal";import ExperienceBanner from "@/components/experience/ExperienceBanner";

export default function RiderRides(){
 const [rides,setRides]=useState<Ride[]>([]);const [pickup,setPickup]=useState("");const [destination,setDestination]=useState("");const [date,setDate]=useState("");const [maxPrice,setMaxPrice]=useState("");const [minSeats,setMinSeats]=useState("");const [sort,setSort]=useState("soonest");const [error,setError]=useState("");
 const search=()=>{const q=new URLSearchParams();if(pickup)q.set("pickup",pickup);if(destination)q.set("destination",destination);if(date)q.set("date",date);fetch(`/api/rides?${q}`).then(r=>r.json()).then(d=>setRides(d.rides||[])).catch(()=>setError("We couldn't refresh rides right now."))};useEffect(search,[]);
 const visible=useMemo(()=>{let out=rides.filter(r=>(!maxPrice||r.pricePerSeat<=Number(maxPrice))&&(!minSeats||r.availableSeats>=Number(minSeats)));return [...out].sort((a,b)=>sort==="price"?a.pricePerSeat-b.pricePerSeat:sort==="seats"?b.availableSeats-a.availableSeats:(a.departureDate+a.departureTime).localeCompare(b.departureDate+b.departureTime))},[rides,maxPrice,minSeats,sort]);
 return <AuthGuard role="RIDER"><DashboardShell role="RIDER"><Stack direction={{xs:"column",sm:"row"}} justifyContent="space-between" alignItems={{sm:"center"}} gap={2}><Box><Typography variant="h3">Find your ride</Typography><Typography sx={{mt:1,color:"text.secondary"}}>Search, filter and compare real published rides. Your next trip is a few taps away.</Typography></Box><Mascot compact/></Stack><ExperienceBanner audience="RIDER" slot="RIDER_FIND_RIDE_BANNER" compact/><Paper elevation={0} sx={{mt:3,p:{xs:2,md:3},border:"1px solid",borderColor:"divider",borderRadius:5}}><Grid container spacing={2}><Grid size={{xs:12,md:6}}><TextField fullWidth label="Pickup" value={pickup} onChange={e=>setPickup(e.target.value)} placeholder="e.g. Pretoria"/></Grid><Grid size={{xs:12,md:6}}><TextField fullWidth label="Destination" value={destination} onChange={e=>setDestination(e.target.value)} placeholder="e.g. Johannesburg"/></Grid><Grid size={{xs:12,sm:6,md:3}}><TextField fullWidth type="date" label="Travel date" InputLabelProps={{shrink:true}} value={date} onChange={e=>setDate(e.target.value)}/></Grid><Grid size={{xs:12,sm:6,md:3}}><TextField fullWidth type="number" label="Max price / seat" value={maxPrice} onChange={e=>setMaxPrice(e.target.value)} placeholder="Any"/></Grid><Grid size={{xs:12,sm:6,md:3}}><TextField fullWidth type="number" label="Seats needed" value={minSeats} onChange={e=>setMinSeats(e.target.value)} placeholder="Any"/></Grid><Grid size={{xs:12,sm:6,md:3}}><TextField fullWidth select label="Sort by" value={sort} onChange={e=>setSort(e.target.value)}><MenuItem value="soonest">Soonest</MenuItem><MenuItem value="price">Lowest price</MenuItem><MenuItem value="seats">Most seats</MenuItem></TextField></Grid><Grid size={{xs:12}}><Stack direction={{xs:"column",sm:"row"}} justifyContent="space-between" alignItems={{sm:"center"}} gap={1}><Typography variant="body2" color="text.secondary">{visible.length} matching ride{visible.length===1?"":"s"}</Typography><Button variant="contained" onClick={search}>Search rides</Button></Stack></Grid></Grid></Paper>{error&&<Alert sx={{mt:2}} severity="error">{error}</Alert>}<Stack gap={2} sx={{mt:3}}>{visible.map((r,i)=><Reveal key={r.id} delay={i*.04}><RideCard ride={r} viewer="RIDER" action={<Button component={Link} href={`/rider/rides/${r.id}`} variant="contained">View & book</Button>}/></Reveal>)}{!visible.length&&<Paper elevation={0} sx={{p:5,textAlign:"center",border:"1px dashed",borderColor:"divider",borderRadius:4}}><Typography variant="h6">No rides match those filters</Typography><Typography color="text.secondary" sx={{mt:1}}>Try a wider date, a higher price limit or fewer seats.</Typography></Paper>}</Stack></DashboardShell></AuthGuard>
}
