"use client";
import { Alert, Box, Button, Checkbox, FormControlLabel, IconButton, InputAdornment, Link as MuiLink, TextField, Typography } from "@mui/material";
import EmailRoundedIcon from "@mui/icons-material/EmailRounded"; import LockRoundedIcon from "@mui/icons-material/LockRounded"; import VisibilityRoundedIcon from "@mui/icons-material/VisibilityRounded"; import VisibilityOffRoundedIcon from "@mui/icons-material/VisibilityOffRounded";
import Link from "next/link"; import { useState } from "react"; import { useRouter } from "next/navigation"; import AuthShell from "@/components/auth/AuthShell"; import AuthCard from "@/components/auth/AuthCard"; import LoadingButton from "@/components/loading/LoadingButton";
export default function LoginPage(){
 const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const [verifyEmail,setVerifyEmail]=useState(""); const [resent,setResent]=useState(""); const [busy,setBusy]=useState(false); const [show,setShow]=useState(false); const router=useRouter();
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");setResent("");try{const r=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok){setError(d.error||"Login failed.");if(d.code==="EMAIL_NOT_VERIFIED")setVerifyEmail(d.email||email);return;}router.replace("/dashboard");}catch{setError("We could not reach ReaGae. Please try again.");}finally{setBusy(false)}};
 return <AuthShell eyebrow="WELCOME BACK"><AuthCard eyebrow="ACCOUNT ACCESS" title="Welcome back" subtitle="Sign in to manage rides, bookings and your verified travel profile.">
  {error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}
  {verifyEmail&&<Box sx={{mb:2,p:1.7,bgcolor:'#FFF8E8',borderLeft:'3px solid #B7791F'}}><Typography variant="body2" fontWeight={750}>Your email still needs verification.</Typography><Button size="small" sx={{mt:.5}} onClick={async()=>{const r=await fetch('/api/auth/resend-verification',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:verifyEmail})});const d=await r.json();setResent(d.message||'Verification email sent.')}}>{resent?'Sent':'Resend verification email'}</Button>{resent&&<Typography variant="caption" display="block" color="success.main">{resent}</Typography>}</Box>}
  <Box component="form" onSubmit={submit}>
   <TextField label="Email or username" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="username" InputProps={{startAdornment:<InputAdornment position="start"><EmailRoundedIcon fontSize="small"/></InputAdornment>}} sx={{mb:2}}/>
   <TextField label="Password" type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password" InputProps={{startAdornment:<InputAdornment position="start"><LockRoundedIcon fontSize="small"/></InputAdornment>,endAdornment:<InputAdornment position="end"><IconButton onClick={()=>setShow(!show)} edge="end" aria-label={show?'Hide password':'Show password'}>{show?<VisibilityOffRoundedIcon/>:<VisibilityRoundedIcon/>}</IconButton></InputAdornment>}}/>
   <Box sx={{display:'flex',justifyContent:'space-between',alignItems:'center',mt:1.2}}><FormControlLabel control={<Checkbox size="small"/>} label={<Typography variant="body2">Remember me</Typography>}/><MuiLink component={Link} href="/forgot-password" underline="hover">Forgot password?</MuiLink></Box>
   <LoadingButton fullWidth type="submit" variant="contained" size="large" loading={busy} sx={{mt:1.5,minHeight:52}} startIcon={<LockRoundedIcon/>}>Sign in securely</LoadingButton>
  </Box>
  <Typography sx={{mt:3,color:'text.secondary',textAlign:'center'}}>New to ReaGae? <MuiLink component={Link} href="/register" underline="hover" fontWeight={800}>Create an account</MuiLink></Typography>
 </AuthCard></AuthShell>;
}
