"use client";
import { Alert, Box, Button, CircularProgress, Stack, TextField, Typography } from "@mui/material";
import LockResetRoundedIcon from "@mui/icons-material/LockResetRounded";
import Link from "next/link";
import { Suspense, useState } from "react";
import { useSearchParams, useRouter } from "next/navigation";
import AuthCard from "@/components/auth/AuthCard";
function ResetForm(){const params=useSearchParams();const router=useRouter();const token=params.get("token")||"";const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const submit=async(e:React.FormEvent)=>{e.preventDefault();setError("");if(!token){setError("This password reset link is missing its security token.");return}if(password!==confirm){setError("The passwords do not match.");return}setBusy(true);const r=await fetch("/api/auth/reset-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,password})});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error||"Unable to reset password.");return}router.replace("/login?reset=success")};return <Box sx={{minHeight:"100vh",display:"grid",placeItems:"center",p:2,background:"radial-gradient(circle at 20% 10%,rgba(121,89,233,.13),transparent 35%),#F6F8FC"}}><AuthCard title="Create a new password" subtitle="Choose a strong password you don't use elsewhere."><Stack alignItems="center" sx={{mb:3}}><Box sx={{width:58,height:58,borderRadius:4,display:"grid",placeItems:"center",bgcolor:"rgba(91,108,255,.1)",color:"primary.main"}}><LockResetRoundedIcon/></Box></Stack>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<Box component="form" onSubmit={submit}><Stack gap={2}><TextField fullWidth type="password" label="New password" value={password} onChange={e=>setPassword(e.target.value)} required helperText="Use at least the requirements shown by ReaGae."/><TextField fullWidth type="password" label="Confirm new password" value={confirm} onChange={e=>setConfirm(e.target.value)} required/><Button fullWidth size="large" variant="contained" type="submit" disabled={busy}>{busy?<><CircularProgress size={20} sx={{mr:1}}/>Updating password…</>:"Change password"}</Button></Stack></Box><Button component={Link} href="/login" sx={{mt:2}}>Back to login</Button></AuthCard></Box>}
export default function ResetPasswordPage(){return <Suspense fallback={<Box sx={{minHeight:"100vh",display:"grid",placeItems:"center"}}><Typography>Loading secure reset…</Typography></Box>}><ResetForm/></Suspense>}
