"use client";
import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Paper, Stack, TextField, Typography } from "@mui/material";
import SupportAgentRoundedIcon from "@mui/icons-material/SupportAgentRounded"; import ReportProblemRoundedIcon from "@mui/icons-material/ReportProblemRounded"; import MicRoundedIcon from "@mui/icons-material/MicRounded"; import UploadFileRoundedIcon from "@mui/icons-material/UploadFileRounded";
import { useRef, useState } from "react"; import { useRouter } from "next/navigation";
const cats=[['UNSAFE_DRIVING','Unsafe driving'],['IDENTITY_CONCERN','Identity concern'],['HARASSMENT','Harassment'],['VEHICLE','Vehicle issue'],['NO_SHOW','No show'],['OTHER','Other']];
export default function RideSafetyActions({bookingId,rideId,afterRide=false}:{bookingId:string;rideId:string;afterRide?:boolean}){
 const router=useRouter();const [dialog,setDialog]=useState<'report'|'support'|'media'|null>(null);const [category,setCategory]=useState('UNSAFE_DRIVING');const [description,setDescription]=useState('');const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);const [recording,setRecording]=useState(false);const recorder=useRef<MediaRecorder|null>(null);const chunks=useRef<Blob[]>([]);
 const report=async()=>{setBusy(true);const r=await fetch('/api/reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bookingId,rideId,category,description})});const d=await r.json();setBusy(false);setMsg(d.error||'Safety concern sent to our safety team.');if(r.ok){setDialog(null);setDescription('')}};
 const support=async()=>{setBusy(true);const r=await fetch('/api/support',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bookingId,subject:'Help with my ReaGae ride',message:'Hi, I need help with this ride.'})});const d=await r.json();setBusy(false);if(!r.ok){setMsg(d.error);return}router.push(`/support/${d.requestId}`)};
 const upload=async(file:File,type:'IMAGE'|'VIDEO')=>{if(file.size>5*1024*1024){setMsg('Keep each safety upload under 5 MB.');return}const reader=new FileReader();reader.onload=async()=>{setBusy(true);const r=await fetch('/api/safety/media',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bookingId,rideId,type,fileName:file.name,mimeType:file.type,data:reader.result})});const d=await r.json();setBusy(false);setMsg(d.error||'Safety evidence saved securely.');if(r.ok)setDialog(null)};reader.readAsDataURL(file)};
 const startRecording=async()=>{if(!navigator.mediaDevices?.getUserMedia){setMsg('Your browser does not support secure audio recording.');return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const r=new MediaRecorder(stream);chunks.current=[];r.ondataavailable=e=>e.data.size&&chunks.current.push(e.data);r.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks.current,{type:r.mimeType||'audio/webm'});if(blob.size>5*1024*1024){setMsg('Recording is too large. Keep it short for safety evidence.');return}const reader=new FileReader();reader.onload=async()=>{setBusy(true);const x=await fetch('/api/safety/media',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bookingId,rideId,type:'AUDIO',fileName:`ride-${bookingId}.webm`,mimeType:blob.type,durationSeconds:60,data:reader.result})});const d=await x.json();setBusy(false);setMsg(d.error||'Conversation recording saved securely.');setDialog(null)};reader.readAsDataURL(blob)};recorder.current=r;r.start();setRecording(true);setTimeout(()=>{if(r.state==='recording'){r.stop();setRecording(false)}},60000)}catch{setMsg('Microphone permission was not granted.')}};
 const stop=()=>{recorder.current?.stop();setRecording(false)};
 return <Stack direction={{xs:'column',sm:'row'}} gap={1} flexWrap="wrap" sx={{mt:2}}>{msg&&<Alert sx={{width:'100%'}} severity="info">{msg}</Alert>}<Button size="small" variant="outlined" startIcon={<SupportAgentRoundedIcon/>} onClick={()=>setDialog('support')}>Contact support</Button><Button size="small" color="error" variant="outlined" startIcon={<ReportProblemRoundedIcon/>} onClick={()=>setDialog('report')}>Report safety concern</Button><Button size="small" variant="outlined" startIcon={<MicRoundedIcon/>} onClick={()=>setDialog('media')}>{afterRide?'Add safety evidence':'Safety recording & evidence'}</Button>
 <Dialog open={!!dialog} onClose={()=>!busy&&setDialog(null)} fullWidth maxWidth="sm"><DialogTitle>{dialog==='report'?'Tell us what happened':dialog==='support'?'Ride support':'Safety recording & evidence'}</DialogTitle><DialogContent><Typography color="text.secondary" sx={{mb:2}}>This is securely attached to ride {rideId.slice(-6)} so our team knows exactly which journey you mean.</Typography>{dialog==='report'&&<Stack gap={2}><TextField select label="Safety category" value={category} onChange={e=>setCategory(e.target.value)}>{cats.map(([v,l])=><MenuItem key={v} value={v}>{l}</MenuItem>)}</TextField><TextField label="What happened?" multiline minRows={4} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Tell us what you need us to know."/></Stack>}{dialog==='support'&&<Paper elevation={0} sx={{p:2.5,bgcolor:'rgba(91,108,255,.08)',borderRadius:3}}><Typography fontWeight={850}>You will be connected to an available ReaGae agent</Typography><Typography color="text.secondary" sx={{mt:1}}>Your request enters the agent queue with this ride and booking already attached. When an agent accepts it, your chat becomes live.</Typography></Paper>}{dialog==='media'&&<Stack gap={2}><Alert severity="info">Safety evidence is optional. Keep up to 3 files per ride, with a 12 MB total limit and 5 MB per file.</Alert><Button component="label" variant="outlined" startIcon={<UploadFileRoundedIcon/>}>Add photo<input hidden type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],'IMAGE')}/></Button><Button component="label" variant="outlined" startIcon={<UploadFileRoundedIcon/>}>Add short video<input hidden type="file" accept="video/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],'VIDEO')}/></Button>{recording?<Button color="error" variant="contained" onClick={stop}>Stop recording</Button>:<Button variant="contained" startIcon={<MicRoundedIcon/>} disabled={busy} onClick={startRecording}>Record up to 60 seconds</Button>}<Typography variant="caption" color="text.secondary">Recording starts only when you choose it and requires microphone permission. ReaGae does not record conversations automatically.</Typography></Stack>}</DialogContent><DialogActions><Button onClick={()=>setDialog(null)} disabled={busy}>Close</Button>{dialog==='report'&&<Button color="error" variant="contained" onClick={report} disabled={busy||description.trim().length<10}>{busy?'Sending…':'Send report'}</Button>}{dialog==='support'&&<Button variant="contained" onClick={support} disabled={busy}>{busy?'Connecting…':'Connect me to support'}</Button>}</DialogActions></Dialog></Stack>}
